apiVersion: v1
kind: Service
metadata:
  name: wordpress2-mysql   # will be used as a value in
  labels:                 # WORDPRESS_DB_HOST in wordpress-deploy.yml
    app: wordpress2
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: wordpress2
    tier: mysql2
---
apiVersion:  apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress2-mysql
  labels:
    app: wordpress2
spec:
  selector:
    matchLabels:
      app: wordpress2
      tier: mysql2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress2
        tier: mysql2
    spec:
      containers:
      - image: mysql:5.6
        name: mysql2
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass        # the one generated before in secret.yml
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data-volume-mysql

      volumes: 
      - name: data-volume-mysql
        hostPath:
          path: /data-mysql/
          type: Directory

