apiVersion: v1
kind: Service
metadata:
  name: wordpress2
  labels:
    app: wordpress2
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
  selector:
    app: wordpress2
    tier: frontend2
#  type: ClusterIP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress2
  labels:
    app: wordpress2
spec:
  selector:
    matchLabels:
      app: wordpress2
      tier: frontend2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress2
        tier: frontend2
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress2
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress2-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass          # generated before in secret.yml
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - mountPath: /var/www/html/
          name: data-volume-wordpress

      volumes: 
      - name: data-volume-wordpress
        hostPath:
          path: /data-wordpress/
          type: Directory

